Adding feature: Hide watched videos on Youtube homepage
OsaSoft/youtube-better-subscriptions pull request #84
Opened 2020-11-24 13:55 UTC by stalha97

Just as this extension hides watched videos on subscription page. With a bit of modification in files, the same feature is extended to homepage of Youtube as well. The UI buttons appear on homepage to enable/disable "hide watched videos" and the other button which makes all the videos on the webpage "watched". And the small icon on individual videos as well, where when you click, that video gets added to "watched" list.

2020-11-25 23:21 UTC, OsaSoft commented
Hi and thanks for the PR!

Ive looked at the code and it seemed weird it would work. I then tested it locally and it really doesnt actually seem to do anything. Please check you have everything pushed

(I also took the liberty to rebase your branch onto develop)

2020-11-26 14:22 UTC, stalha97 commented
Hi, thanks for your reply. I have tested it again locally and it is working. I checked the code on develop branch and apparently there have been a lot of changes than when I programmed on it and I think that messed up with the work I did. I am attaching an image of what I am seeing with what I originally coded on.

![image](https://user-images.githubusercontent.com/61848531/100361900-8dbb1e00-301c-11eb-8fd6-07a8b1096662.png)

2020-11-26 22:35 UTC, OsaSoft requested changes
Ive ran it again locally and for some reason it seems to have broken the functionality added in the previous MR (only show the Mark as watched button on thumbnail hover), it now doesnt show on hover. (at least for me testing using Chrome, havent tested in Firefox)

If you can fix that great, if not no big deal and Ill still merge the PR and just disable that feature for now, as it seems a bit unreliable in the way its currently implemented.

Thanks!

2020-11-26 22:35 UTC, OsaSoft commented on manifest.json
> +  "version": "0.14",
pls change back, version is updated before release (though Ill probably change this process in the future)

2020-11-26 22:35 UTC, OsaSoft commented on pageHandler.js
> +		"home": ""
please fix indents. Tabs -> spaces

2020-11-26 22:35 UTC, OsaSoft commented on pageHandler.js
> +				case PAGES.home:
please fix indents. Tabs -> spaces

2020-12-25 19:49 UTC, OsaSoft commented
ok, since the PR has been inactive for some time and requested changes are minor, I shall do them manually. But for future PRs, they will be closed after some time of inactivity

2020-12-25 19:49 UTC, merged